### ISSUE TITLE
O aplicativo diz que eu não executei como admininstrador mesmo tendo executado.

### ISSUE THREAD

**Issue by 1mrtz** [Teramanbr/TerabyteTweaker#1]
O aplicativo diz que eu não executei como admininstrador mesmo tendo executado.
![Screenshot_2](https://user-images.githubusercontent.com/107440986/173453050-e004e3c4-78d2-4ea9-a5d8-7c303ce7fc42.png)

**Comment by Teramanbr** [comment]
acabei de testar no meu e não tá dando nenhum aviso, mas vou dar outra checada no código
![image](https://user-images.githubusercontent.com/71410827/173597279-65bcc739-1f11-4493-b5fa-4a5dc50e384b.png)

**Comment by Teramanbr** [comment]
Vou aproveitar e dar uma atualizada nele, inclusive, você baixou a versão mais recente?

**Comment by 1mrtz** [comment]
agora foi, baixei dnv e consegui, obg

**Comment by Teramanbr** [comment]
Problema resolvido e arquivado.
