### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HashNotAsh** [Teramanbr/TerabyteTweaker#10]
**Describe the bug:**
I can't use the restore point on my computer because of my antivirus not being able to copy.

**Expected behavior:**
It was supposed to revert all changes the optimizer made.

**Screenshots:**
I have no screenshot currently.

**Desktop:**
 - OS: Windows 10
 - OS Version: 21H2

**Extra information:**
I can't also turn off my pc due to the power plan configurations being deleted because i forgot to turn off the power optimizer plan

**Comment by HashNotAsh** [comment]
also my discord is
"lywoh"
if you want to talk with me personally.

**Comment by Teramanbr** [comment]
Issue addressed on discord, caused by the use of an antivirus software during the installation.
