### ISSUE TITLE
[ENHANCEMENT]Are you busy?

### ISSUE THREAD

**Issue by nabbiriri** [Teramanbr/TerabyteTweaker#11]
Thank you for creating a great program.
However, the program or the YouTube update has not been updated for a long time, so I am wondering if it is no longer being developed. I hope you will leave a message often.

Thanks.

**Comment by Teramanbr** [comment]
Oh, hey there, I actually got some free time, I just tend to forget about this program...
Well, I plan to remake it all in another language, Batch isn't really an option anymore.
When I first started making this program, I was like... 12 years old? Yeah, this stuff is a bit old, but it sure does work for now.

I'm actually in college right now, so I might learn python and remake the program fully from the ground up.
Thx for your preoccupation, apologies for the bad English and apologies for not updating my program in a long time.

**Comment by nabbiriri** [comment]
I am Korean, so I write this using a translator.
Thank you for the quick reply and I hope you have a great college life and a good future.
