### ISSUE TITLE
[BUG] Everything runs even slower after using

### ISSUE THREAD

**Issue by PangwenE** [Teramanbr/TerabyteTweaker#12]
Title says it all, in VALORANT I'm getting even more stutters than before and webpages take longer to load, I have an RTX 3070

**Comment by Teramanbr** [comment]
Well, you seem to have been the first person experiencing something like this.
There should be a Restore Point on your computer to undo Terabyte Tweaker's changes.
Open your search bar, then write "Restore Point", should be the first option.
Then click on System Restore and select Terabyte Tweaker's Restore Point.
Sorry for the delayed answer, but I hope I could help you for now.

As you were the first person with this problem, this sadly will be marked as 'can't duplicate'.
