### ISSUE TITLE
Stutters/Fps Drops in Valorant.

### ISSUE THREAD

**Issue by gearvlr** [Teramanbr/TerabyteTweaker#13]
I was looking for some tweaking programs and i found this. I quickly installed it and tried to play a game. In game my fps dropped to 16-130 from 220-300. I can't play anything anymore. I tried to revert everything the program did using system restore point. And it gave me an error. I resetted my pc and it's still the same.

**Comment by Teramanbr** [comment]
Did you turn off your antivirus before running the program like mentioned in the [Installing](https://github.com/Teramanbr/TerabyteTweaker#installing) tutorial? If not, then your antivirus may have stopped Terabyte Tweaker from running the script on it's fullest, and so, the restore point may have bricked, and the script won't have ran properly.
The antivirus breaking scripts is a very known problem and the reason for me to put on a warning about turning off the antivirus before running it.

**Comment by gearvlr** [comment]
Thank you, I forgot to turn the antivirus off ;-;

**Comment by Teramanbr** [comment]
Well, sadly, there's not much I can do, then.
I recommend an in-place reinstallation, that way, you'll keep everything while reinstalling windows (that's also good for FPS in general)
Here's a tutorial on how to do it: https://www.youtube.com/watch?v=CAOwN68AInE
I wish you luck.
