### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Camper10** [Teramanbr/TerabyteTweaker#2]
Whenever i run the .bat file as administrator it still throws up this error(below)
![image](https://user-images.githubusercontent.com/78254974/183150810-9596f64d-a3cf-4fcd-baa0-ca542037f29f.png)

**Comment by Teramanbr** [comment]
Someone else also had this same problem, make sure to download the latest version from [this](https://github.com/Teramanbr/TerabyteTweaker/releases/latest/download/Terabyte.Tweaker.bat) link.
Also, remember that some antiviruses flag batch files as viruses, if the problem persists then you should try turning it off while using the tweaker.

**Comment by Teramanbr** [comment]
Since you are the second person to run into this problem, i will check the code myself and try to find something that is conflicting.

**Comment by Camper10** [comment]
Still the problem persists

**Comment by Teramanbr** [comment]
What steps have you done to try and stop this from happening?

**Comment by Camper10** [comment]
Nothing.

**Comment by Teramanbr** [comment]
Which windows version do you use?
Name and version please.

Also, if you have done no troubleshooting steps, then why?
common solutions to batch files not working are:
- restarting your computer
- disabling antiviruses
- allowing permissions
- if not enabled, enable UAC (user account control) and manually select allow

**Comment by Teramanbr** [comment]
I have updated the application, could you try and download the new version and try it out to check if the problem gets fixed?

**Comment by Teramanbr** [comment]
Could you please respond ASAP? or else I will have to close this issue report tommorow, thanks in advance.

**Comment by Teramanbr** [comment]
Due to inactivity, this issue was closed.
