### ISSUE TITLE
[BUG] power plan is balanced?

### ISSUE THREAD

**Issue by RicUnknown** [Teramanbr/TerabyteTweaker#3]
my power plan is balanced after running terabyte, is that intentional?

**Comment by Teramanbr** [comment]
Depends, did your connection to the internet got down mid installation? if so, Terabyte Tweaker wasn't able to download the power plan and automatically set it to balanced instead.
Either that or you disabled Power Plan Tweaking in the settings, make sure this is set to true:
![image](https://user-images.githubusercontent.com/71410827/188326963-aaf00a2d-8197-4250-a608-dd16acff0219.png)
