### ISSUE TITLE
[FAQ] connection to the internet

### ISSUE THREAD

**Issue by andika207** [Teramanbr/TerabyteTweaker#5]
**Warning: For the app to run, you NEED to have a connection to the internet.**

any reason why a bat file would ever require internet connetion ?

**Comment by andika207** [comment]
what files does it download and where do they go ?

**Comment by andika207** [comment]
@Teramanbr one month later..... still waiting for a reply brazuca !

**Comment by Teramanbr** [comment]
You could just have clicked on the github src folder, it is an open source program...

**Comment by Teramanbr** [comment]
I thought that was obvious and you figured it out after not asking anything again for 1 month.
