### ISSUE TITLE
[BUG] Fingerprint scanner stops working

### ISSUE THREAD

**Issue by izzatsksk** [Teramanbr/TerabyteTweaker#7]
**Describe the bug:**
After restarting, my fingerprint scanner stops working.  However, my pin lock is working properly. I have try to uninstall and install the driver but to no avail, it isn’t working either

**Expected behavior:**

**Screenshot**

![CA7879E8-6D3B-4C4A-8325-3E8D43A75456](https://user-images.githubusercontent.com/72776236/194021492-2d48dac8-d15e-4842-98f0-8779e09d7de1.jpeg)

![D264D2B2-B6BD-41F9-8811-FEBD4673EDB0](https://user-images.githubusercontent.com/72776236/194021502-69cb73e4-7d0e-44cd-a26f-659b8e90d6fa.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Version: 22H2

**Additional context**

**Comment by Teramanbr** [comment]
Here is how to use a restore point:
Open Start, Search for Create a restore point and click the top result to open the System Properties page.
Under the "System Protection"  section, click system restore, click next and select Terabyte Tweaker.

If the problem was caused by Terabyte Tweaker or something installed after then it will be undone.

**Comment by izzatsksk** [comment]
> Here is how to use a restore point: Open Start, Search for Create a restore point and click the top result to open the System Properties page. Under the "System Protection" section, click system restore, click next and select Terabyte Tweaker.
> 
> If the problem was caused by Terabyte Tweaker or something installed after then it will be undone.

**Comment by izzatsksk** [comment]
By the time i saw this, i just realized that i ran the terabyte tweaker without administrator which the restore point didn't show in the system. So, i went reinstalling it back and the restore point is there but it is the one that i've done recently like i said. Still trying to figure out how to restore the fingerprint scanner issues.

On another note: The terabyte tweaker also change the mode when the laptop lid closed. It changes from "sleep" to "do nothing". Its not a bug, just wanted to let everyone know this if people didn't realized it

**Comment by Teramanbr** [comment]
After you mentioned "i ran the terabyte tweaker without administrator", I quickly went into the code and noticed the part that warns you about administrator privileges was disabled.
The next update will feature the fix, i already fixed the source file.
