### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nanunamzzy** [Teramanbr/TerabyteTweaker#8]
![image](https://user-images.githubusercontent.com/103026989/207647563-34304675-3efe-46d8-a2eb-34f44d9cdb21.png)
 
 I can't change, create power plan. Your powerplan is good but it's crashing my pc and my cpu fan is really loud even while browsing. and i can't restore my system too :D it got one drive error and restore failed 
 I'm on windows 10 pro 64bit

**Comment by Teramanbr** [comment]
Issue adressed on Discord, Problem fixed.
